services:
  wedding-app:
    image: iliutaadrian/wedding-website:latest
    container_name: wedding-website
    restart: always
    ports:
      - "3025:3000"
    environment:
      - NODE_ENV=production
