services:
  wedding-app:
    image: iliutaadrian/wedding-website:latest
    container_name: wedding-website
    restart: always
    ports:
      - "3025:3000"
    volumes:
      - ./suggestions.json:/app/suggestions.json
    env_file:
      - .env.local
    environment:
      - NODE_ENV=production
